#!/usr/bin/env bash

COMPOSE="docker compose --env-file=.docker/.env"

if [ $# -gt 0 ];then

    # Run artisan commands inside backend container
    if [ "$1" == "art" ] || [ "$1" == "artisan" ]; then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/backend \
            backend \
            php artisan "$@"

    # Run composer commands inside backend container
    elif [ "$1" == "composer" ]; then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/backend \
            backend \
            composer "$@"

    # Run npm commands inside frontend container
    elif [ "$1" == "npm" ]; then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/frontend \
            frontend \
            npm "$@"

    # Run npx commands inside frontend container
    elif [ "$1" == "npx" ]; then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/frontend \
            frontend \
            npx "$@"
    # Whatever other commands will run as docker command
    else
        $COMPOSE "$@"
    fi

# By default, on invoke this command without arguments will show a list 
# of containers currently running
else
    $COMPOSE ps
fi
