#!/usr/bin/env bash

export APP_ENV=${APP_ENV:-local}
export APP_PORT=${APP_PORT:-80}

COMPOSE="docker compose --env-file=.docker/.env"

if [ $# -gt 0 ];then

    if [ "$1" == "art" ] || [ "$1" == "artisan" ]; then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/backend \
            backend \
            php artisan "$@"

    elif [ "$1" == "composer" ]; then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/backend \
            backend \
            composer "$@"

    elif [ "$1" == "test" ]; then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/backend \
            backend \
            ./vendor/bin/phpunit "$@"

    elif [ "$1" == "npm" ]; then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/frontend \
            frontend \
            npm "$@"

    elif [ "$1" == "npx" ]; then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/frontend \
            frontend \
            npx "$@"

    else
        $COMPOSE "$@"
    fi

else
    $COMPOSE ps
fi
